apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mgmt
  labels:
    app: user-mgmt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-mgmt
  template:
    metadata:
      labels:
        app: user-mgmt
    spec:
      containers:
        - name: user-mgmt
          image: user-mgmt_image:latest
          ports:
            - containerPort: 80
