# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: user-mgmt-app  
#   namespace: argocd     
# spec:
#   project: default      
#   source:
#     repoURL: https://github.com/TudoTechnologies/DevPlazaBackendInternal.git  
#     targetRevision: testcases_testing  
#     path: k8s-manifests  
#   destination:
#     server: https://kubernetes.default.svc  
#     namespace: argocd  
#   syncPolicy:
#     automated:
#       prune: true        
#       selfHeal: true    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80