apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mgmt-app  # Name of your ArgoCD application
  namespace: argocd     # The namespace where ArgoCD is installed
spec:
  project: default      # Project in ArgoCD (default project here)
  source:
    repoURL: https://github.com/TudoTechnologies/DevPlazaBackendInternal.git  # GitHub repo URL (your project source code)
    targetRevision: testcases_testing  # Git branch to track (could be 'main', 'master', etc.)
    path: k8s-manifests  # Path inside the repo where your Kubernetes manifests are located
  destination:
    server: https://kubernetes.default.svc  # The Kubernetes API server
    namespace: argocd  # The Kubernetes namespace where the resources will be deployed
  syncPolicy:
    automated:
      prune: true        # Automatically prune deleted resources from the cluster
      selfHeal: true     # Automatically heal drifted resources